name: Main Configuration file for orchestration of pipeline

on:
  push:
    branches: ["main"]

jobs:
  Build-And-Publish:
    uses: ts-software-solutions/mule-sample-project/.github/workflows/build.yml@main
    secrets: inherit

  Deploy-to-DEV:    
    needs: Build-And-Publish
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@main
    secrets: inherit
    with: 
      mule-env: 'DEV'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}
  
  Deploy-to-UAT:    
    needs:  Build-And-Publish
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@main
    secrets: inherit
    with: 
      mule-env: 'UAT'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}
  
  Deploy-to-PROD:    
    needs:  Build-And-Publish
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@main
    secrets: inherit
    with: 
      mule-env: 'PROD'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}

  Deployment-Cleanup:
    needs:  Build-And-Publish
    uses: ts-software-solutions/mule-sample-project/.github/workflows/post-deployment-tasks.yml@main 
    with:
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}