name: Test and build Jar File 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        #cache: maven
    - name: Configure Maven settings
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: |
          [
            {
              "id": "anypoint-exchange-v3",
              "username": "~~~Client~~~",
              "password": "${{ secrets.MULE_CLIENT_ID }}~?~${{ secrets.MULE_CLIENT_SECRET }}"
            },
            {
              "id": "avio-mulesoft-ee-releases",
              "username": "${{ secrets.MULE_EE_REPO_USERNAME }}",
              "password": "${{ secrets.MULE_EE_REPO_PASSWORD }}"
            }
          ]
        mirrors: |
          [
            {
              "id": "avio-mulesoft-ee-releases",
              "name": "avio-mulesoft-ee-releases",
              "mirrorOf": "mule-repository",
              "url": "https://devops.avioconsulting.com/nexus/repository/mulesoft-ee-releases/"
            }
          ]
   
    - name: test with Maven
      run: mvn clean test -e -U -Dmule.env=dev -Dmule.key=${{ secrets.MULE_DEV_CRYPTO_KEY }} 