name: Test and build Jar File 

on:
  workflow_call:
    secrets:
      MULE_DEV_CRYPTO_KEY: 
        required: true
      MULE_EE_REPO_USERNAME: 
        required: true
      MULE_EE_REPO_PASSWORD: 
        required: true
      MULE_CLIENT_ID: 
        required: true
      MULE_CLIENT_SECRET: 
        required: true
      GH_PAT: 
        required: true
    inputs:
      build-test: 
        description: Specify whether you would like to build the jar file or just run unit tests
        required: false
        type: string
        default: 'test'
      early-access-name: 
        description: The name of the tag and release of the prerelease that will be created
        required: false
        type: string
        default: 'early-access'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    # Checkout current branch
    - uses: actions/checkout@v4
      with:
        ref: ${{ GITHUB.ref }}
        token: ${{ secrets.GH_PAT }}
    
    # Setup java and maven settings
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
   
    - name: Configure Maven settings
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        servers: >
          [
            {
              "id": "anypoint-exchange-v3",
              "username": "~~~Client~~~",
              "password": "${{ secrets.MULE_CLIENT_ID }}~?~${{ secrets.MULE_CLIENT_SECRET }}"
            },
            {
              "id": "avio-mulesoft-ee-releases",
              "username": "${{ secrets.MULE_EE_REPO_USERNAME }}",
              "password": "${{ secrets.MULE_EE_REPO_PASSWORD }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "avio-mulesoft-ee-releases",
              "name": "avio-mulesoft-ee-releases",
              "mirrorOf": "MuleRepository",
              "url": "https://devops.avioconsulting.com/nexus/repository/mulesoft-ee-releases/"
            }
          ]
        repositories: >
          [
            { 
              "id": "MuleRepository", 
              "name": "MuleRepository", 
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/", 
              "releases": { 
                "enabled": "true" 
              }, 
              "snapshots": { 
                "enabled": "true" 
              } 
            }
          ]
        active_profiles: >
          [
            "github"
          ]
        output_file: .m2/settings.xml

    
    #### *** If inputs.build-test == 'test' *** ####  
    # Run MUnit Tests
    - name: Run Unit Tests
      if: ${{ inputs.build-test == 'test' }}
      run: mvn clean test -e -U -s ./.m2/settings.xml -Denv=dev -Dcrypto.key=${{ secrets.MULE_DEV_CRYPTO_KEY }}

    - name: |
        Ensure all branches are within convention. Branches should be prefixed by feature, fix, or hotfix followed by '/'
        branches should include the user that completed the work's github username in all lowercase followed by '/'
        Finally a short description of the work done in snake case
        ex: feature/tannersherman/add-new-field-to-addresses
      if: ${{ inputs.build-test == 'test' }}
      uses: deepakputhraya/action-branch-name@master
      with:
        regex: '(feature|fix|hotfix)\/([a-z]{1,15})\/([a-z0-9-]{1,50})|release\-[a-zA-Z0-9]{7}' # Regex the branch should match. This example enforces grouping
        allowed_prefixes: '' # All branches should start with the given prefix
        ignore: main # Ignore exactly matching branch names from convention
        min_length: 5 # Min length of the branch name
        max_length: 100 # Max length of the branch name

    #### *** If inputs.build-test == 'build' *** ####
    - name: Set Version Number based on Date and build number
      if: ${{ inputs.build-test == 'build' }}
      id: version
      run: |
        echo BUILD_NUMBER=${{ github.run_number }} >> $GITHUB_OUTPUT
        echo CURR_DATE=$(date +'%d%m%Y') >> $GITHUB_OUTPUT
    
    - name: Set Pom Version
      if: ${{ inputs.build-test == 'build' }}
      run: mvn versions:set "-DnewVersion=1.0.${{ steps.version.outputs.CURR_DATE }}${{ steps.version.outputs.BUILD_NUMBER }}"

    - name: Build Jar
      if: ${{ inputs.build-test == 'build' }}
      run: |
        mvn clean package \
        -e -U -s ./.m2/settings.xml \
        -Denv=dev \
        -Dcrypto.key=${{ secrets.MULE_DEV_CRYPTO_KEY }} \
        -DmuleDeploy.appArtifact=./target/mule-sample-project-1.0.${{ steps.version.outputs.CURR_DATE }}${{ steps.version.outputs.BUILD_NUMBER }}-mule-application.jar

    - name: Get Jar Full File Name
      run: |
        echo "FILE_PATH=$(ls ./target/*.jar)" >> $GITHUB_OUTPUT
        echo "delimiter=target/"
        echo "FILE_NAME=${FILE_PATH#*$delimiter}" >> $GITHUB_OUTPUT
      id: file_properties

    - name: Create tag if not exists, if it does, update
      if: ${{ inputs.build-test == 'build' }}
      uses: richardsimko/update-tag@v1
      with:
        tag_name: ${{ inputs.early-access-name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check if early-access Release already exists
      id: checkRelease
      uses: cardinalby/git-get-release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ inputs.early-access-name }} 
        prerelease: true
        doNotFailIfNotFound: true

    - name: Delete the early-access release if an old one exists
      if: ${{ steps.checkRelease.outputs.tag_name == inputs.early-access-name }}
      uses: cb80/delrel@latest
      with:
        tag: ${{ inputs.early-access-name }}
        token: ${{ secrets.GH_PAT }}

    - name: Create prerelease for early-access
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.early-access-name }}
        release_name: ${{ inputs.early-access-name }}
        draft: false
        prerelease: true

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.file_properties.outputs.FILE_PATH }}
        asset_name: mule-sample-project-1.0.${{ steps.version.outputs.CURR_DATE }}${{ steps.version.outputs.BUILD_NUMBER }}-mule-application.jar
        asset_content_type: application/java-archive