name: Test and build Jar File 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        #cache: maven
    - name: Configure Maven settings
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        servers: >
          [
            {
              "id": "anypoint-exchange-v3",
              "username": "~~~Client~~~",
              "password": "${{ secrets.MULE_CLIENT_ID }}~?~${{ secrets.MULE_CLIENT_SECRET }}"
            },
            {
              "id": "avio-mulesoft-ee-releases",
              "username": "${{ secrets.MULE_EE_REPO_USERNAME }}",
              "password": "${{ secrets.MULE_EE_REPO_PASSWORD }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "avio-mulesoft-ee-releases",
              "name": "avio-mulesoft-ee-releases",
              "mirrorOf": "MuleRepository",
              "url": "https://devops.avioconsulting.com/nexus/repository/mulesoft-ee-releases/"
            }
          ]
        profiles: >
          [
            {
              "id": "Mule",
              "repositories": [
                 {
                    "id": "MuleRepository",
                    "name": "MuleRepository",
                    "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/",
                    "releases": {
                      "enabled": "true"
                    },
                    "snapshots": {
                      "enabled": "false"
                    }
                 } 
              ]
            }
          ]
        active_profiles: >
          [
            "Mule"
          ]
        output_file: .m2/settings.xml
    - name: Display settings.xml contents
      run: cat ./.m2/settings.xml
      shell: bash
    - name: test with Maven
      run: mvn clean test -e -U -Dmule.env=dev -Dmule.key=${{ secrets.MULE_DEV_CRYPTO_KEY }} 