name: Test and build Jar File 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        #cache: maven
    - name: Configure Maven settings
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        servers: >
          [
            {
              "id": "anypoint-exchange-v3",
              "username": "~~~Token~~~",
              "password": "${{ secrets.TS_TOKEN }}"
            },
            {
              "id": "avio-releases",
              "username": "${{ secrets.MULE_EE_REPO_USERNAME }}",
              "password": "${{ secrets.MULE_EE_REPO_PASSWORD }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "avio-releases",
              "name": "avio-releases",
              "mirrorOf": "mulesoft-releases",
              "url": "https://devops.avioconsulting.com/nexus/repository/mulesoft-releases/"
            }
          ]
   
    - name: test with Maven
      run: mvn clean test -e -U -Dmule.env=dev -Dmule.key=${{ secrets.MULE_DEV_CRYPTO_KEY }} 