name: Main Configuration file for orchestration of pipeline

on:
  push:
    branches: ["main"]

jobs:
  Build-And-Publish:
    uses: ts-software-solutions/mule-sample-project/.github/workflows/build.yml@main
    secrets: inherit

  Deploy-to-Dev:    
    needs: Build-And-Publish
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@main
    secrets: inherit
    with: 
      mule-env: 'DEV'
      short-sha: ${{ needs.Build-And-Publish.outputs.short-sha }}
  
  # Create-release-branch
  Deploy-to-UAT:    
    needs: [ Build-And-Publish, Deploy-to-Dev ]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@main
    secrets: inherit
    with: 
      mule-env: 'UAT'
      short-sha: ${{ needs.Build-And-Publish.outputs.short-sha }}

  Deployment-Cleanup:
    needs: [ Build-And-Publish, Deploy-to-Dev, Deploy-to-UAT ]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/post-deployment-tasks.yml@main 
    with:
      tag-version: ${{ needs.Build-And-Publish.outputs.app-version }}