name: Deploy to Dev

on:
  workflow_call:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: app-artifacts
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Display structure of downloaded files
      run: ls -R