name: Deploy workflow

on:
  workflow_call:
    secrets:
      CRYPTO_KEY: 
        required: true
      MULE_CLIENT_ID: 
        required: true
      MULE_CLIENT_SECRET: 
        required: true
      ANYPOINT_CLIENT_ID: 
        required: true
      ANYPOINT_CLIENT_SECRET: 
        required: true
      GH_PAT: 
        required: true
    inputs:
      mule-env: 
        description: The MuleSoft environment that the deployment will be deployed to
        required: true
        type: string
      tag-name:
        description: The tag name used in the build stage so the release can be fetched
        required: true
        type: string

        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Get Files from early-access release and extract zip file
      uses: robinraju/release-downloader@v1.8
      with: 
        tag: "${{ inputs.tag-name }}"
        fileName: "*.jar"
        tarBall: false
        zipBall: true
        out-file-path: "release_assets"
        extract: true
        token: ${{ secrets.GH_PAT }}

    - name: Get paths to source code and jar
      id: get_paths
      run: |
        echo "SOURCE_CODE=$(ls -1 -d release_assets/*mule-sample-project*/)" >> $GITHUB_OUTPUT
        echo "JAR_FILE=$(ls release_assets/*.jar)" >> $GITHUB_OUTPUT

    - name: Copy POM and Jar into working directory
      run: |
        cp ${{ steps.get_paths.outputs.SOURCE_CODE }}/pom.xml .
        cp ${{ steps.get_paths.outputs.JAR_FILE }} .
        pwd
        ls

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Deploy To specified environment based on profile
      run: |
        mvn mule:deploy -e -P ${{ inputs.mule-env }} \
        -Dmule.key=${{ secrets.CRYPTO_KEY }} \
        -DartifactPath=~/${{ steps.get_paths.outputs.JAR_FILE }} \
        -DconnectedAppClientId=${{ secrets.MULE_CLIENT_ID }} \
        -DconnectedAppClientSecret=${{ secrets.MULE_CLIENT_SECRET }} \
        -DanypointPlatformClientId=${{ secrets.ANYPOINT_CLIENT_ID }} \
        -DanypointPlatformClientSecret=${{ secrets.ANYPOINT_CLIENT_SECRET }} 