name: Main Configuration file for orchestration of pipeline

on:
  push:

jobs:
  Run-Tests:
    if: ${{ && GITHUB.ref_name != 'main' }}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/build.yml@main
    secrets: inherit

  Build-And-Publish:
    if: ${{ && GITHUB.ref_name == 'main' }}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/build.yml@main
    secrets: inherit
    with:
      build-test: 'build'