name: Main Configuration file for orchestration of pipeline

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
  release: 

jobs:
  Run-Tests:
    if: ${{ GITHUB.ref_name != 'main' && github.event_name != 'release'}}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/build.yml@main
    secrets: inherit

  Build-And-Publish:
    if: ${{ GITHUB.ref_name == 'main' && github.event_name != 'release'}}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/build.yml@main
    secrets: inherit
    with:
      build-test: 'build'

  Deploy-To-Dev:
    if: ${{ github.event_name == 'release' }}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      tag-name: 'early-access'
      mule-env: 'DEV'