name: Main Configuration file for orchestration of pipeline

on:
  push:
    branches: ["develop", "release-*", "main"]
  pull_request:
    branches: ["develop", "release-*", "main"]

jobs:
  Run-Tests:
    if: ${{ GITHUB.event_name == 'pull_request' }}
    uses: ts-software-solutions/mule-sample-project/.github/workflows/test.yml@develop
    secrets: inherit

  Build-And-Publish:
    if: ${{ GITHUB.event_name != 'pull_request' }}
    uses: ts-software-solutions/mule-sample-project/.github/workflows/build.yml@develop
    secrets: inherit

  Deploy-to-DEV:
    if: ${{ GITHUB.event_name != 'pull_request' && GITHUB.ref_name != 'main'}}
    needs: [Build-And-Publish]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@develop
    secrets: inherit
    with: 
      mule-env: 'DEV'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}
  
  Deploy-to-UAT:
    if: ${{ GITHUB.event_name != 'pull_request' && GITHUB.ref_name != 'main'}}
    needs: [Build-And-Publish]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@develop
    secrets: inherit
    with: 
      mule-env: 'UAT'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}
  
  Deploy-to-PROD:
    if: ${{ GITHUB.event_name != 'pull_request' }}
    needs: [Build-And-Publish]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@develop
    secrets: inherit
    with: 
      mule-env: 'PROD'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}

  Branch-Cleanup:
    if: ${{ GITHUB.event_name != 'pull_request' }}
    needs: [Build-And-Publish, Deploy-to-PROD]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/branch-cleanup.yml@develop
    secrets: inherit 
    with:
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}

  Create-Tag:
    if: ${{ GITHUB.event_name != 'pull_request' }}
    needs: [Build-And-Publish, Deploy-to-PROD, Branch-Cleanup]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/create-tag.yml@develop
    secrets: inherit 
    with:
      tag-name: ${{ needs.Build-And-Publish.outputs.short-sha }}
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}