name: Main Configuration file for orchestration of pipeline

on:
  push:
    branches: ["develop"]

jobs:
  Build-And-Publish:
    uses: ts-software-solutions/mule-sample-project/.github/workflows/build.yml@develop
    secrets: inherit

  Deploy-to-DEV:    
    needs: [Build-And-Publish]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@develop
    secrets: inherit
    with: 
      mule-env: 'DEV'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}
  
  Deploy-to-UAT:    
    needs: [Build-And-Publish, Deploy-to-DEV]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@develop
    secrets: inherit
    with: 
      mule-env: 'UAT'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}
  
  Deploy-to-PROD:    
    needs: [Build-And-Publish, Deploy-to-DEV, Deploy-to-UAT]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/deploy.yml@develop
    secrets: inherit
    with: 
      mule-env: 'PROD'
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}

  Deployment-Cleanup:
    needs: [Build-And-Publish, Deploy-to-DEV, Deploy-to-UAT, Deploy-to-PROD]
    uses: ts-software-solutions/mule-sample-project/.github/workflows/post-deployment-tasks.yml@develop 
    with:
      tag-name: ${{ needs.Build-And-Publish.outputs.short-sha }}
      release-branch: ${{ needs.Build-And-Publish.outputs.release-branch }}