name: Deployment Pipeline

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
  release: 

jobs:
  Run-Tests:
    if: ${{ GITHUB.ref_name != 'main' && github.event_name != 'release'}}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/build.yml@main
    secrets: inherit

  Build-And-Publish:
    if: ${{ GITHUB.ref_name == 'main' && github.event_name != 'release'}}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/build.yml@main
    secrets: inherit
    with:
      build-test: 'build'

  Deploy-To-Dev:
    if: ${{ github.event_name == 'release' }}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/deploy.yml@main
    secrets:
      CRYPTO_KEY: ${{ secrets.MULE_DEV_CRYPTO_KEY }} 
      MULE_CLIENT_ID: ${{ secrets.MULE_CLIENT_ID }} 
      MULE_CLIENT_SECRET: ${{ secrets.MULE_CLIENT_SECRET }} 
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }} 
      ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }} 
      GH_PAT: ${{ secrets.GH_PAT }} 
    with:
      tag-name: 'early-access'
      mule-env: 'DEV'
  
  Deploy-To-UAT:
    if: ${{ github.event_name == 'release' }}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/deploy.yml@main
    needs: [Deploy-To-Dev]
    secrets:
      CRYPTO_KEY: ${{ secrets.MULE_DEV_CRYPTO_KEY }} 
      MULE_CLIENT_ID: ${{ secrets.MULE_CLIENT_ID }} 
      MULE_CLIENT_SECRET: ${{ secrets.MULE_CLIENT_SECRET }} 
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }} 
      ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }} 
      GH_PAT: ${{ secrets.GH_PAT }} 
    with:
      tag-name: 'early-access'
      mule-env: 'UAT'

  Deploy-To-Prod:
    if: ${{ github.event_name == 'release' }}
    uses: ts-software-solutions/ghf-mule-sample-project/.github/workflows/deploy.yml@main
    needs: [Deploy-To-Dev, Deploy-To-UAT]
    secrets:
      CRYPTO_KEY: ${{ secrets.MULE_PROD_CRYPTO_KEY }} 
      MULE_CLIENT_ID: ${{ secrets.MULE_CLIENT_ID }} 
      MULE_CLIENT_SECRET: ${{ secrets.MULE_CLIENT_SECRET }} 
      ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }} 
      ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }} 
      GH_PAT: ${{ secrets.GH_PAT }} 
    with:
      tag-name: 'early-access'
      mule-env: 'PROD'


    # Create offical tag and release
