name: Main Configuration file for orchestration of pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-And-Publish:
    uses: ts-software-solutions/mule-sample-project/.github/workflows/build.yml@main
    secrets: 
      MULE_DEV_CRYPTO_KEY: ${{ secrets.MULE_DEV_CRYPTO_KEY }}
      MULE_EE_REPO_USERNAME: ${{ secrets.MULE_EE_REPO_USERNAME }}
      MULE_EE_REPO_PASSWORD: ${{ secrets.MULE_EE_REPO_PASSWORD }}
      MULE_CLIENT_ID: ${{ secrets.MULE_CLIENT_ID }}
      MULE_CLIENT_SECRET: ${{ secrets.MULE_CLIENT_SECRET }}