name: After Prod Deployment Tasks

on:
  workflow_call:
    inputs:
      tag-name: 
        description: name of which to create the tag
        required: true
        type: string
      release-branch: 
        description: The name of the release branch to delete
        required: true
        type: string
      main-branch: 
        description: Name of the main branch used. default to main
        required: false
        type: string
        default: 'main'
      develop-branch: 
        description: Name of the develop branch used. default to develop
        required: false
        type: string
        default: 'develop'


jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout release branch
      uses: actions/checkout@v4
      with: 
        ref: ${{ inputs.release-branch }}
    
    - name: Retrieve tag exists flag
      uses: mukunku/tag-exists-action@v1.4.0
      id: checkTag
      with:
        tag: ${{ inputs.tag-name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify and create tag if not exists
      if: ${{ steps.checkTag.outputs.exists == 'false' }}
      uses: mathieudutour/github-tag-action@v6.1
      with:
        default_bump: false
        custom_tag:  ${{ inputs.tag-name }}
        tag_prefix: ""
        github_token: ${{ secrets.GITHUB_TOKEN }}
  
  merge-release:
    runs-on: ubuntu-latest
    if: ${{ GITHUB.ref_name != 'main' }}
    steps:
    
    - name: Checkout release branch
      uses: actions/checkout@v4
      with: 
        ref: ${{ inputs.release-branch }}
    
    - name: Merge release -> develop
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ secrets.GH_PAT }}
        source_ref: ${{ inputs.release-branch }}
        target_branch: ${{ inputs.develop-branch }}
        commit_message_template: 'Merge release branch into dev branch [skip ci]'
    
    - name: Merge release -> main
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ secrets.GH_PAT }}
        source_ref: ${{ inputs.release-branch }}
        target_branch: ${{ inputs.main-branch }}
        commit_message_template: 'Merge release branch into main branch [skip ci]'


  
  merge-main-into-dev:
    runs-on: ubuntu-latest
    if: ${{ GITHUB.ref_name == 'main' }}
    steps:
    - name: Checkout release branch
      uses: actions/checkout@v4
      with: 
        ref: ${{ inputs.release-branch }}
    
    - name: Merge release -> develop
      uses: everlytic/branch-merge@1.1.2
      with:
        github_token: ${{ secrets.GH_PAT }}
        source_ref: ${{ inputs.main-branch }}
        target_branch: ${{ inputs.develop-branch }}
        commit_message_template: 'Merge hotfix implementation into develop and start new pipeline'

  delete-release-branch:
    runs-on: ubuntu-latest
    if: ${{ GITHUB.REF_NAME != 'main' }}
    needs: merge-release
    steps:
    - name: Delete branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: ${{ inputs.release-branch }}