name: After Prod Deployment Tasks

on:
  workflow_call:
    inputs:
      tag-version:
        required: true
        type: string

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Tag 
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ inputs.tag-version }}
          github_token: ${{ secrets.GH_PAT }}
          message: "Latest release"