name: After Prod Deployment Tasks

on:
  workflow_call:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get short commit tag
        id: vars
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          message: "Latest release"
          commit_sha: ${{ steps.vars.outputs.SHA_SHORT }}