name: Test Code 

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    # Checkout current branch
    - uses: actions/checkout@v3
    
    # Setup java and maven settings
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Configure Maven settings
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        servers: >
          [
            {
              "id": "anypoint-exchange-v3",
              "username": "~~~Client~~~",
              "password": "${{ secrets.MULE_CLIENT_ID }}~?~${{ secrets.MULE_CLIENT_SECRET }}"
            },
            {
              "id": "avio-mulesoft-ee-releases",
              "username": "${{ secrets.MULE_EE_REPO_USERNAME }}",
              "password": "${{ secrets.MULE_EE_REPO_PASSWORD }}"
            }
          ]
        mirrors: >
          [
            {
              "id": "avio-mulesoft-ee-releases",
              "name": "avio-mulesoft-ee-releases",
              "mirrorOf": "MuleRepository",
              "url": "https://devops.avioconsulting.com/nexus/repository/mulesoft-ee-releases/"
            }
          ]
        repositories: >
          [
            { 
              "id": "MuleRepository", 
              "name": "MuleRepository", 
              "url": "https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/", 
              "releases": { 
                "enabled": "true" 
              }, 
              "snapshots": { 
                "enabled": "true" 
              } 
            }
          ]
        active_profiles: >
          [
            "github"
          ]
        output_file: .m2/settings.xml

    # Run MUnit Tests
    - name: Build Jar
      run: mvn clean test -e -U -s ./.m2/settings.xml -Dmule.env=DEV -Dmule.key=${{ secrets.MULE_DEV_CRYPTO_KEY }}